/**
 * Batch / Bundle Generator for @peerbits/fhir-observation-generator.
 *
 * Converts an array of DeviceReading objects into a FHIR transaction Bundle.
 * Formatted for direct execution with @peerbits/fhir-client's batch/transaction builder.
 */

import { DeviceReading, FhirBundle, FhirR5Bundle, GeneratorConfig } from "./types.js";
import { toObservation, toR5Observation } from "./generators/index.js";

export function readingsToBundle(
  readings: DeviceReading[],
  config?: GeneratorConfig
): FhirBundle {
  if (!Array.isArray(readings)) {
    throw new Error("Invalid input to readingsToBundle: expected array of DeviceReading objects");
  }

  const entries = readings.map((reading) => {
    const observation = toObservation(reading, config);
    return {
      resource: observation,
      request: {
        method: "POST" as const,
        url: "Observation",
      },
    };
  });

  return {
    resourceType: "Bundle",
    type: "transaction",
    entry: entries,
  };
}

/**
 * Converts readings into a FHIR R5 transaction Bundle.
 *
 * Vital-sign data generated by this package uses fields common to both FHIR R4
 * and R5; this function provides an explicit R5-typed integration boundary.
 */
export function readingsToR5Bundle(
  readings: DeviceReading[],
  config?: GeneratorConfig
): FhirR5Bundle {
  if (!Array.isArray(readings)) {
    throw new Error("Invalid input to readingsToR5Bundle: expected array of DeviceReading objects");
  }

  return {
    resourceType: "Bundle",
    type: "transaction",
    entry: readings.map((reading) => ({
      resource: toR5Observation(reading, config),
      request: {
        method: "POST",
        url: "Observation",
      },
    })),
  };
}
